### ISSUE TITLE
Simplified Chinese Localization files (v0.8.4c) upolad

### ISSUE THREAD

**Issue by aloneangel34** [regret-index/Administrix-Mod#3]
[Simplified Chinese Localization_084c.zip](https://github.com/regret-index/Administrix-Mod/files/2762787/Simplified.Chinese.Localization_084c.zip)

**Important !**:
Beside the Simplified Chinese translation Localization files, there is also a file called "Translation Notes.txt".

You mentioned that there would be a person who would check the translation, so I made this file for him/her. 

**In this file, I explained why I translated some words in that ways (especially if he/she don't know much about Touhou Project) and talked about where I was not sure about my translation.**

**HOWEVER, this "Translation Notes.txt" was written in Chinese**, so if your friend is also a Chinese, it maybe helpful; if not, then you can just ignore it.

**Comment by regret-index** [comment]
One mega-update later...

[ZHS_092 (INCOMPLETE).zip](https://github.com/regret-index/Administrix-Mod/files/3131172/ZHS_092.INCOMPLETE.zip)

**Comment by aloneangel34** [comment]
[ZHS_092 (COMPLETED).zip](https://github.com/regret-index/Administrix-Mod/files/3132897/ZHS_092.COMPLETED.zip)

Since 0.9.2 has not been released, I didn't test it in-game.
--------------
A recommendation:
About Xian Arts, better make sure its Card Description and its Power Description stay the same

now:
in Card Description: The first time each turn you gain any Artifact, ……
in Power Description: Whenever you gain any Artifact, ……

**Comment by aloneangel34** [comment]
There are 2 problem with the last upload AdministrixMod-CardStrings-ZHS.json
1. About "Trick of the Light"
I misread "Discard the top Plot card in your draw pile" as "Discard the top card in your draw pile"
2. Miss a "," in card "Just rewards" which may cause crash

all fixed here
[AdministrixMod-CardStrings-ZHS_092_v2.zip](https://github.com/regret-index/Administrix-Mod/files/3133296/AdministrixMod-CardStrings-ZHS_092_v2.zip)

**Comment by aloneangel34** [comment]
something is wrong with v0.9.2 when language is set to Simplified Chinese
after start the game, ModTheSpire reports errors

here is the error log
[error.log](https://github.com/regret-index/Administrix-Mod/files/3224526/error.log)

BTW, I opened the game without mod and changed the language setting to English
and then tried to start the game with v0.9.2, it worked normally.
